name: Build and deploy action
on:
  push:
    branches:
      - 'main'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: Echo gitHubname and repo
        run: echo ${{ github.repository }}/${{ github.ref_name }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./precode
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/heroesapp:${{ github.ref_name }}-version-${{ github.run_id }}
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat precode/docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          source: "deploy/docker-compose.yaml"
          target: "heroesapp"
          strip_components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          script: |
            cd heroesapp
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d