name: Build and deploy action
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
    - name: run docker-compose
        run: |
          $(echo ~$SSH_USERNAME/heroesapp)