name: Build and deploy action
on:
  push:
    branches:
      - 'main'
jobs:
  validate-env-vars:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: "sssssss"
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
      - name: Print Global Environment Variables
        run: echo $FOO
      - name: Print Job Environment Variables
        run: |
          echo ~$SSH_USERNAME/heroesapp