name: Build and deploy action
on:
  push:
    branches:
      - 'main'
jobs:
  validate-env-vars:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
      - name: clone code
        run: echo $FOO
      - name: Print Job Environment Variables